.TH WAAAA 6 2017-11-27 "" "Games Manual"
.SH NAME
.B waaaa
\- a game about shouting
.SH SYNOPSIS
.SY waaaa
.YS
.SH DESCRIPTION
.B waaaa
is a simple two-player game where the players fight
to control a ball and put it in the other player's basket.
The game is played using the microphone - as you shout, the floor reacts accordingly,
hurling the ball into the air. Tone your voice appropriately to steer the ball and score points!
.SH LICENSE
.B waaaa
is available under the terms of the GNU General Public
License, version 3, as published by the Free Software Foundation.
.SH AUTHOR
Written by Sebastian Krzyszkowiak at PolyJam 2017 (Global Game Jam in Warsaw, Poland).
